### ISSUE TITLE
Error Playing Videos from YouTube | Linux Machine

### ISSUE THREAD

**Issue by Algerization** [ysdragon/StreamBot#66] opened 2024-10-29 17:02 UTC
![image](https://github.com/user-attachments/assets/71db278a-f07c-48d8-8e1e-f5c43b594f55)

While trying to Play a video using link/title.

**Comment by Algerization** [comment] 2024-10-29 17:14
> Can you try to pull the repo and try again?

Same issue.
![image](https://github.com/user-attachments/assets/1343b231-fa77-47de-860a-5dee7fd16af2)

**Comment by ysdragon** [comment] 2024-10-29 17:15
Weird, i don't have such an issue, and i can't reproduce it.
Can you tell me the steps to reproduce?

**Comment by Algerization** [comment] 2024-10-29 17:16
> Weird, i don't have such an issue, and i can't reproduce it. Can you tell me the steps to reproduce?

I don't really know. Try to fix it.

**Comment by ysdragon** [comment] 2024-10-29 17:17
What command did you use?

**Comment by ysdragon** [comment] 2024-10-29 17:20
It's an issue from your side then...
Error 466 indicates that there have been too many requests.

**Comment by ysdragon** [comment] 2024-10-29 17:50
I'm able to reproduce it now, if you done many requests to yourube.

**Comment by Algerization** [comment] 2024-10-29 17:51
It was only 1 request. Reproduce it please

**Comment by Algerization** [comment] 2024-10-29 18:09
> Please pull the repo now and try again.

![image](https://github.com/user-attachments/assets/2eb87c16-fb4a-4500-9cd9-d0f981136b2f)

**Comment by ysdragon** [comment] 2024-10-29 18:11
Run remove node_modules, bun.lockb and run bun install, then `bun run build && bun run start`

**Comment by ysdragon** [comment] 2024-10-29 18:11
The issue has been fixed for me so, i will close the issue now.

**Closed by ysdragon** 2024-10-29 18:11 UTC

**Comment by Algerization** [comment] 2024-10-29 18:13
> Run remove node_modules, bun.lockb and run bun install, then `bun run build && bun run start`

rm: cannot remove 'node_modules': Is a directory

**Comment by ysdragon** [comment] 2024-10-29 18:17
rm -rf node_modules bun.lockb
Please go learn some of the Linux basics.

**Comment by Algerization** [comment] 2024-10-29 18:22
> rm -rf node_modules bun.lockb

U didn't fix the issue, Still facing the same Issue.. How is it working file for you? can you upload your version? I will clone it and try to run it to check
