### ISSUE TITLE
Issue with Pause/Resume Command

### ISSUE THREAD

**Issue by Abruccii** [ysdragon/StreamBot#55] opened 2024-10-12 17:24 UTC
First of all, sorry for my bad english guys.

So i currently try to play .mkv files with StreamBot under Windows as my Jellyfin Server runs under Windows with GPU Acceleration and the StreamBot should run on the same server so it can access the video files.

Playing the movie works without any issue. if i try to pause the movie, the script crashes as SIGSTOP seems to be a unknown signal. 

StreamBot uses [dank074/Discord-video-stream](https://github.com/dank074/Discord-video-stream) as source and there seems to be a pull request that seems to enable pause/resume. can this be implemented? https://github.com/dank074/Discord-video-stream/pull/93/commits/1d48f42e217bb511040ccfed66ca374f9d519663

Alternatively there seems to be Signals NtSuspendProcess and NtResumeProcess to get this working under Windows, altough i don't know how to accomplish this.

Any solutions?

**Comment by ysdragon** [comment] 2024-10-12 17:34
Duplicate of #18 issue.
You should run the bot under Linux instead, windows is not supported right now.

**Closed by ysdragon** 2024-10-12 17:34 UTC
