### ISSUE TITLE
Add video queue, video scrubbing and possibly audio codec selection

### ISSUE THREAD

**Issue by JeshMate** [ysdragon/StreamBot#46] opened 2024-08-31 14:58 UTC
Basically what the title says, I made a bot ages ago with these features but i never learnt how to do typescript like how this one is made, I'm still learning how to use it but you may be able to get at it faster than I can.

**Comment by ysdragon** [comment] 2024-08-31 15:01
Duplicate of #39

**Closed by ysdragon** 2024-08-31 15:01 UTC
