### ISSUE TITLE
Plays for roughly 5 seconds then stops

### ISSUE THREAD

**Issue by CharlieSavage95** [ysdragon/StreamBot#67] opened 2024-10-30 14:45 UTC
When running the bot it will play the first 5-10 seconds roughly of a video (youtube or local) then it leaves the voice channel, no errors in the console, just leaves

**Comment by ysdragon** [comment] 2024-10-30 20:16
Hi @CharlieSavage95
I can't reproduce the issue, seems like to be an issue from your side.

**Comment by awakcon1234** [comment] 2024-10-31 07:38
I got the same issue while playing local or youtube video. Interestingly my bot don't stop when playing a youtube live or twitch stream generated with `streamlink`.

**Comment by ysdragon** [comment] 2024-10-31 14:29
Weird, it's working fine for me.
Can you try to run the bot using nodejs
1. `npx tsc` 
2.  `node dist/index.js`

**Comment by awakcon1234** [comment] 2024-11-01 02:24
Welp, that's working fine for me too, I can play through a 20 mins long video without crashing.

Also I tried running with latest bun on my machine, I got this error spammed in my console:

```
❯ bun run build
$ bunx tsc
❯ bun run start
$ bun ./dist/index.js
Available videos:

--- haisenberger is ready ---
Started playing video
ERROR 363 |   };
364 |   if (!connected)
365 |     state.handle.lookup(address, afterDns);
366 |   else
367 |     afterDns(null, null);
368 | function doSend(ex, self, ip, list, address, port, callback) {
                     ^
EAGAIN: Try again
   errno: -11
 syscall: "send"

      at doSend (node:dgram:368:16)
      at node:dgram:360:18
      at node:dns:28:36

ERROR 363 |   };
364 |   if (!connected)
365 |     state.handle.lookup(address, afterDns);
366 |   else
367 |     afterDns(null, null);
368 | function doSend(ex, self, ip, list, address, port, callback) {
                     ^
EAGAIN: Try again
   errno: -11
 syscall: "send"

      at doSend (node:dgram:368:16)
      at node:dgram:360:18
      at node:dns:28:36

ERROR 363 |   };
364 |   if (!connected)
365 |     state.handle.lookup(address, afterDns);
366 |   else
367 |     afterDns(null, null);
368 | function doSend(ex, self, ip, list, address, port, callback) {
                     ^
EAGAIN: Try again
   errno: -11
 syscall: "send"

      at doSend (node:dgram:368:16)
      at node:dgram:360:18
      at node:dns:28:36

ERROR 363 |   };
364 |   if (!connected)
365 |     state.handle.lookup(address, afterDns);
366 |   else
367 |     afterDns(null, null);
368 | function doSend(ex, self, ip, list, address, port, callback) {
                     ^
EAGAIN: Try again
   errno: -11
 syscall: "send"

      at doSend (node:dgram:368:16)
      at node:dgram:360:18
      at node:dns:28:36

[ABOVE ERROR SPAMMED HERE]

Bun v1.1.33 (Linux x64)
error: script "start" exited with code 1
  ~/discord-stream-local   main ❯
```

No error logs shown while running inside container with `docker compose logs`, but it will send **Finished playing video.** message in the command channel before it stop the playback.

**Comment by ysdragon** [comment] 2024-11-01 04:28
Seems to be an issue from bun.

**Comment by ysdragon** [comment] 2024-11-01 04:29
I'll look for a solution later.

**Comment by awakcon1234** [comment] 2024-11-01 13:30
@ysdragon I'm using v22.4.1

**Comment by ysdragon** [comment] 2024-11-01 13:47
Try to pull the repo now and try again.

**Comment by awakcon1234** [comment] 2024-11-01 15:42
I pulled the latest docker image and tested it, can't play video with `play` and `playlink`, got this log from docker:

```
streambot  |
streambot  | > streambot@1.1.0 start /home/bots/StreamBot
streambot  | > node ./dist/index.js
streambot  |
streambot  | Available videos:
streambot  | civ1
streambot  | civ2
streambot  | mark1
streambot  | mark123
streambot  | mark2
streambot  | markhp666.3
streambot  | nokotan
streambot  | (node:18) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
streambot  | (Use `node --trace-deprecation ...` to show where the warning was created)
streambot  | --- haisenberger is ready ---
streambot  | Started playing video
streambot  | Playing ( civ1 )...
streambot  |  ELIFECYCLE  Command failed.
streambot  |
streambot  | > streambot@1.1.0 start /home/bots/StreamBot
streambot  | > node ./dist/index.js
streambot  |
streambot  | Available videos:
streambot  | civ1
streambot  | civ2
streambot  | mark1
streambot  | mark123
streambot  | mark2
streambot  | markhp666.3
streambot  | nokotan
streambot  | (node:18) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
streambot  | (Use `node --trace-deprecation ...` to show where the warning was created)
streambot  | --- haisenberger is ready ---
streambot  | Error: getaddrinfo EAI_AGAIN hongkong11003.discord.media
streambot  |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
streambot  |   errno: -3001,
streambot  |   code: 'EAI_AGAIN',
streambot  |   syscall: 'getaddrinfo',
streambot  |   hostname: 'hongkong11003.discord.media'
streambot  | }
streambot  | Stopped playing
streambot  | Started playing video
streambot  |  ELIFECYCLE  Command failed.
streambot  |
streambot  | > streambot@1.1.0 start /home/bots/StreamBot
streambot  | > node ./dist/index.js
streambot  |
streambot  | Available videos:
streambot  | civ1
streambot  | civ2
streambot  | mark1
streambot  | mark123
streambot  | mark2
streambot  | markhp666.3
streambot  | nokotan
streambot  | (node:18) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
streambot  | (Use `node --trace-deprecation ...` to show where the warning was created)
streambot  | --- haisenberger is ready ---
```

**Comment by ysdragon** [comment] 2024-11-01 17:03
You can try to change your dns @CharlieSavage95 
So, I will close this issue now.

**Closed** 2024-11-01 17:03 UTC
